# configs/9v.yml

name: 9vids
domain: 9vids.com
base_url: "http://www.9vids.com"
selector_style: css
name_suffix: " - 9vids"

modes:
  video:
    url_pattern: "{video_id}"
    scraper: video_scraper
  search:
    url_pattern: "/?s={search}"
    scraper: list_scraper

download:
  command: 'curl -L -o "{destination_path}" -A "{user_agent}" "{url}"'

scrapers:
  video_scraper:
    title:
      selector: "meta[itemprop='name']"
      attribute: "content"
    download_url:
      selector: "meta[itemprop='contentURL']"
      attribute: "content"

  list_scraper:
    video_container:
      selector:
        - "body"
    video_item:
      selector: "div.video-block.thumbs-rotation"
      fields:
        url:
          selector: "a.infos"
          attribute: "href"
        title:
          selector: "a.infos"
          attribute: "title"
    pagination:
      next_page:
        selector: "a.next.page-numbers"
        attribute: "href"

video_key_pattern: "/"

url_encoding_rules:
  " ": "+"
