# configs/lf.yml

name: LoneFun
domain: lonefun.com
base_url: "https://lonefun.com"
selector_style: css
name_suffix: " - LONEFUN"

url_encoding_rules:
  " ": "+"

modes:
  video:
    url_pattern: "/watch/{video_id}"
    scraper: video_scraper
  search:
    url_pattern: "/search?keyword={search}"
    scraper: list_scraper

download:
  command: 'curl -L -o "{destination_path}" -A "{user_agent}" "{url}"'

scrapers:
  video_scraper:
    title:
      selector: "h2.tag_video_title"
    download_url:
      selector: "video source"
      attribute: "src"
    description:
      selector: "meta[name='description']"
      attribute: "content"
    tags:
      selector: "meta[name='keywords']"
      attribute: "content"

  list_scraper:
    video_container:
      selector:
        - "div.row.tag_video_grid.author-list.videos-latest-list"
    video_item:
      selector: "div.video-list.tag_video_grid_list"
      fields:
        url:
          selector: "a.position-relative.d-block.thumb"
          attribute: "href"
        title:
          selector: "h4 a"
        views:
          selector: "div.foot"
          regex: '(\d+,?\d*)\s+Views'
        duration:
          selector: "div.duration"
    pagination:
      first_page: "{url_pattern}"
      subsequent_pages: "{url_pattern}&page_id={page}"
      max_pages: 999


video_key_pattern: "/watch/"
